#!/usr/bin/env bash
# script that will display information about subdomains

# Function to display subdomain information
display_subdomain_info() {
  local domain=$1
  local subdomain=$2
  local record_type

  if [[ -z $subdomain ]]; then
    subdomains=("www" "lb-01" "web-01" "web-02")
  else
    subdomains=("$subdomain")
  fi

  for sub in "${subdomains[@]}"; do
    record_type=$(dig ${sub}.${domain} | awk '/ANSWER SECTION/ {getline; print $4}')
    destination=$(dig ${sub}.${domain} | awk '/ANSWER SECTION/ {getline; print $5}')
    echo "The subdomain ${sub} is a ${record_type} record and points to ${destination}"
  done
}

# Check command-line arguments
if [[ $# -eq 0 ]]; then
  echo "Missing domain argument"
  exit 1
elif [[ $# -eq 1 ]]; then
  domain=$1
  display_subdomain_info $domain
elif [[ $# -eq 2 ]]; then
  domain=$1
  subdomain=$2
  display_subdomain_info $domain $subdomain
else
  echo "Invalid number of arguments"
  exit 1
fi

