#!/usr/bin/env bash
# A script that transfers a file from our client to a server

source_file=$1
destination_ip=$2
username=$3
ssh_key=$4


ssh() {
	scp -o "StrictHostKeyChecking=no" -i ssh_keysource_file username@destination_ip:~/
}

if [ "$#" != "4" ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	ssh
fi
