#!/usr/bin/env bash
# An automated script

string="Hello World!"
redirect_path="\n\tlocation /redirect_me {\n\t\treturn 301 https://youtu.be/dQw4w9WgXcQ; \n\t}\n"
conf_file="/etc/nginx/sites-available/default"
html_pages="/var/www/html/404.html"
error_404="Ceci n'est pas une page"
error_path="\n\terror_page 404 /404.html;\n\tlocation = /404.html {\n\t\tinternal;\n\t}\n"
custom_header="\n\tadd_header X-Served-By $(hostname);"

# Update and upgrade packages
sudo apt-get update
sudo apt-get -y upgrade

# Install nginx
sudo apt-get install -y nginx

# Set the custom configuration
sudo echo "$string" > /var/www/html/index.nginx-debian.html
sudo sed -i "37i\ $redirect_path" "$conf_file"
sudo echo "$error_404" > "$html_pages"
sudo sed -i "41i\ $error_path" "$conf_file"

# Set the custom response header in Nginx configuration
sudo sed -i "37i\ $custom_header" /etc/nginx/nginx.conf

# Restart Nginx to apply the changes
sudo service nginx restart

