#!/usr/bin/env bash
# a Bash script that configures a new Ubuntu machine

# Update and upgrade packages
sudo apt-get update
sudo apt-get -y upgrade

# Install HAProxy
sudo apt-get -y install haproxy

# Configure HAProxy
sudo sed -i 's/^ENABLED=0/ENABLED=1/' /etc/default/haproxy

# Configure HAProxy backend servers
sudo bash -c "cat > /etc/haproxy/haproxy.cfg" << EOF
frontend lb
    bind *:80
    mode http
    timeout client 30s
    default_backend webservers

backend webservers
    mode http
    balance roundrobin
    timeout server 30s
    timeout connect 30s
    server web-01 217377-web-01:80 check
    server web-02 217377-web-02:80 check
EOF

# Configure name resolution 
echo -e "\n100.25.143.147\t217377-web-01\n35.153.194.199\t217377-web-02" >> /etc/hosts

# Restart HAProxy
sudo service haproxy restart
