#!/usr/bin/env bash
# A script that manages manage_my_process

if [ "$#" -eq 0 ]; then
  echo "Usage: manage_my_process {start|stop|restart}"
  exit 1
fi

process="/var/run/my_process.pid"

start_process() {
	nohup ./manage_my_process &>/dev/null &
	echo $! > "$process"
	printf "manage_my_process started\n"
	exit 0
}

stop_process() {
	pid=$(cat "$process")
	kill -s SIGSTOP "$pid"
	rm -f "$process"
	printf "manage_my_process stopped\n"
	exit 0
}

restart_process() {
	pid=$(cat "$process")
        kill -s SIGSTOP "$pid"
        rm -f "$process"
	./manage_my_process &
        echo $! > "$process"
	printf "manage_my_process restarted\n"
	exit 0
}

case $1 in
  start)
    start_process
    ;;
  stop)
    stop_process
    ;;
  restart)
    restart_process
    ;;
  *)
    echo "Usage: manage_my_process {start|stop|restart}"
    exit 1
    ;;
esac

