#!/usr/bin/env bash
# A script that manages manage_my_process

if [ "$#" -eq 0 ]; then
  echo "Usage: manage_my_process {start|stop|restart}"
  exit 1
fi

process="/var/run/my_process.pid"

start_process() {
	nohup ./manage_my_process &>/dev/null &
	echo $! > "$process"
	exit 0
}

stop_process() {
	pid=$(cat "$process")
	kill "$pid"
	rm -f "$process"
	exit 0
}

restart_process() {
	start_process
	stop_process
	exit 0
}

case $1 in
	start)
		start_process
		printf "manage_my_process started\n"
		;;
	stop)
		stop_process
		printf "manage_my_process stopped\n"
		;;
	restart)
		restart_process
		printf "manage_my_process restarted\n"
		;;
	*)
		echo "Usage: manage_my_process {start|stop|restart}"
		exit 1
		;;
esac

