#!/usr/bin/env bash
# A script that displays the content of the file /etc/passwd,
# using the while loop + IFS

while IFS=: read -r username password user_id group_id comment home_dir shell; do
	echo "The user $username is part of the $group_id gang, lives in $home_dir and rides $shell. $user_id's place is protected by the passcode $password, more info about the user here: $comment"
done < /etc/passwd
