#!/usr/bin/env bash
# This script tha loops from 1 to 10
# displays bad luck for the 4th loop iteration
# displays good luck for the 8th loop iteration
# displays Best School for the other iterations

num1=0
num2=10
while [ $num1 -lt $num2 ]; do
        ((num1++))

	if [ $num1 == 4 ]
	then
		printf "bad luck\n"
	elif [ $num1 == 8  ]
	then
		printf "good luck\n"
	else
		printf "Best School\n"
	fi
done
