#!/usr/bin/env bash
# This script tha loops from 1 to 20
# displays 4 and then bad luck from China for the 4th loop iteration
# displays 9 and then bad luck from Japan for the 9th loop iteration
# displays 17 and then bad luck from Italy for the 17th loop iteration

num1=0
num2=21
while [ $num1 -lt $num2 ]; do
        ((num1++))
	printf "%d\n" "$num1"

	case $num1 in
		4)
			printf "bad luck from China\n"
			;;
		9)
			printf "bad luck from Japan\n"
			;;
		17)
			printf "bad luck from Italy\n"
			;;
		*)
			;;
	esac
done
