#!/usr/bin/env bash
# A bash scripts that displays
# The content of the current directory
# In a list format
# Where only the part of the name after the first dash is displayed

for item in *; do
	ls "$item" | cut -f2  -d"-";
done	
