#!/usr/bin/env bash
# A script that give information about the School file

file="./school"
if [ -e "$file" ]
then
	printf "school file exists\n"

	if [ -s "$file" ]
	then
		printf "school file is not empty\n"

	else
		printf "school file is empty\n"
	fi

	if [ -f "$file" ]
                then
                printf "school is a regular file\n"
                fi

else
	printf "school file does not exist\n"
fi
