#!/usr/bin/env bash
# install the ufw firewall and setup a few rules

# Installation of UFW
sudo apt-get update
sudo apt-get install ufw

# Set the default incoming policy to deny
sudo ufw default deny incoming

# Allow SSH (port 22) connections
sudo ufw allow 22/tcp

# Allow HTTPS (port 443) connections
sudo ufw allow 443/tcp

# Allow HTTP (port 80) connections
sudo ufw allow 80/tcp

# Enable ufw
sudo ufw enable
