#!/usr/bin/env bash
# A script that configures an Ubuntu server

cp /etc/hosts ~/hosts.new
sed -i s/127.0.0.1/127.0.0.2/ ~/hosts.new
echo -e "8.8.8.8 \t facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
