#!/usr/bin/env bash
# A script that configures an Ubuntu server

cp /etc/hosts /etc/hosts.new
sed -i s/127.0.0.1/127.0.0.2/ /etc/hosts.new
echo -e "8.8.8.8 \t facebook.com" >> /etc/hosts.new
cp -f /etc/hosts.new /etc/hosts
