#!/usr/bin/env bash
# A script that displays all active IPv4 IPs on the machine it’s executed on

#ifconfig | grep "inet " | awk '{print $2}' | cut -d: -f
#ifconfig | grep inet | cut -f-10 -d" " | cut -f10- -d" "
ifconfig | grep inet | awk '{print $2}'
