#!/bin/bash
# fix short and sweet
sudo sed -i 's/user  nginx;/user  nginx;\ndaemon off;/' /etc/nginx/nginx.conf
sudo sed -i 's/# server_names_hash_bucket_size 64;/server_names_hash_bucket_size 64;/' /etc/nginx/nginx.conf
sudo sed -i '/listen\s*80;/a listen 8080;' /etc/nginx/conf.d/default.conf
sudo chown -R nginx:nginx /var/www/html
sudo service nginx start
